name: shinas_koya_portfolio
description: "A new Flutter project for portfolio."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  responsive_builder: ^0.7.1
  rxdart: ^0.28.0
  provider: ^6.1.2
  flutter_svg: ^2.0.17
  intl: ^0.20.2
  flutter_smart_dialog: ^4.9.7+8
  url_launcher: ^6.3.1
  url_launcher_web: ^2.3.3
  share_plus: ^10.1.2





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true



  assets:
    - assets/
    - assets/icons/
    - assets/images/
